### PR TITLE
Support running service under user and group

### PR DESCRIPTION
**Pull request by pizzapim**

### CODE REVIEW

**Comment by pizzapim** [comment]
@MagicRB What is your stance on the init systems other than `dinit`? Do you think it is worth implementing the user and group options for those init systems as well? Because with this change, the `dnsmasq` service will only be available under `dinit`.

**Comment by MagicRB** [comment]
You're asking a very very very hard question. I initially created this project because I wanted to give myself and others init freedom. Kind of like Artix. But now I kind of see that making not completely whack code and supporting multiple inits is hard. Take for example `shutdownOnExit`, it's whacked, but nothing much can be done there because `runit` and `dinit` implement that option in completely different ways. If at some point we would want NixNG to run on real hardware, then `runit` goes out the window anyway because "keep restarting things until it works" is not a good way to write an init system. So I don't know. For maintenance sake we should probably throw `runit` out, `dumb-init` with it and possibly shove in `s6`, if not that we could just drop the  whole abstraction and set `dinit` as the one true init.

**Comment by MagicRB** [comment]
I would call on the users of NixNG to chip in here, but there aren't that many :/

**Comment by pizzapim** [comment]
I do think having an abstraction layer above the init system, like NixNG currently has, is a good way to go. We should refrain from introducing options that only a small subset of init systems would support (with NixOS as the extreme where all SystemD options are supported of course). So in my mind, the `user` and `group` options are okay because they are/can be implemented with most init systems.

**Comment by MagicRB** [comment]
Definitely, but my concern is more of maintenance. As in, if `runit` breaks, will either of notice?

**Comment by pizzapim** [comment]
Yeah, good point. I don't know about your deployments, but mine are all on `dinit` by now so I would indeed not notice. We could partly address this by implementing tests.

**Comment by MagicRB** [comment]
Looks good to me, there is a slight problem of say, `atticd`module creates its own user `attic`, if I want to run it under `foobar` i cannot really undo the creation of the `attic` user since there is no way to "unset" an option in the NixOS module system. Bu that's a general problem we should ignore probably as its shared by NixOS too.

**Comment by MagicRB** [comment]
Think you broke something @pizzapim  :)

**Comment by MagicRB** [comment]
Ah maybe not actually I think I know why it broke.

**Comment by MagicRB** [comment]
Welp, i wanted to create a PR, but I pressed the wrong key in Emacs and pushed it to master, :shrug:

**Pull request merged**
